# Build file originally from jcabi/jcabi-aspects under the following license:
# 
# Copyright (c) 2012-2016, jcabi.com
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met: 1) Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer. 2) Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials provided
# with the distribution. 3) Neither the name of the jcabi.com nor
# the names of its contributors may be used to endorse or promote
# products derived from this software without specific prior written
# permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
# NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
# THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
# 

version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  MAVEN_PROJECT_PACKAGE_NAME: fallk.logmaster
  nodejs_version: "8"
  matrix:
    #- JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  access_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ
    
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Install maven
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile('http://www.us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip', 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.5.0\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: SET MAVEN_OPTS=-Xmx4g
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5
  - cmd: SET JAVA_OPTS=-Xmx4g
  - cmd: mvn --version
  - cmd: java -version
before_build:
  - cmd: mvn versions:set -DnewVersion=rev%APPVEYOR_BUILD_NUMBER% -DgenerateBackupPoms=false
build_script:
  # clean wipes stuff, site generates the site, deploy generates the repo
  # i think i can merge deploy into site so it doesn't have to run things twice?
  - mvn clean deploy site -B -Dmaven.test.skip=true
  #- mvn clean package -B -Dmaven.test.skip=true
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Maven test
  - mvn test
  #- mvn clean install --batch-mode -Pqulice
  
after_deploy:
  # push to gh-pages
  # setup git credentials
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "app@veyor.build"
  - git config --global user.name "Appveyor CI"
  # clone gh-pages branch to separate folder
  - cmd: mkdir %USERPROFILE%\gh-pages
  - git clone --quiet --branch=gh-pages https://github.com/uwx/logmaster %USERPROFILE%\gh-pages
  # update the xml
  - cmd: set USERDIR=%USERPROFILE%\gh-pages
  - node _testhash
  #
  - cmd: dir
  - cmd: cmd /c copyfiles
#C:\projects\jfunktion-p0doj\  
  - cmd: set LASTDIR=%CD%
  - cmd: cd %USERPROFILE%\gh-pages
  - cmd: dir
  - git add -f .
  - cmd: cmd /c %LASTDIR%\trycommit.bat
  - git push origin gh-pages

cache:
#  - C:\maven\
  - C:\Users\appveyor\.m2
  
artifacts:
  # pushing a single file
  - path: target\*.jar

deploy:
  tag: 'rev$(appveyor_build_version)'
  release: 'Logmaster r$(appveyor_build_version)'
  description: 'Built from branch $(APPVEYOR_REPO_BRANCH) at $(APPVEYOR_REPO_COMMIT_TIMESTAMP).'
  
  provider: GitHub
  auth_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ # your encrypted token from GitHub
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    #appveyor_repo_tag: true        # deploy on tag push only

notifications:
  - provider: Slack
    on_build_success: true
    on_build_failure: true
    incoming_webhook:
      secure: +5y63VhkKwOZVK264xwgH8gp7vI2cJivXvseQeSoYYNyH3wjOtid8Qz+gyNOjCGpI/xqxxJNwqFrL75ZPHYOYEKs9WhBWznTsFpJUAs5hxn1kcczMv6WYuwUzXJNEdqX6m47PnS7xrzUZJIRWNQCHRJCtN5VX+hXfVV6BT+tKQdRDeRr/LANhRLr2pAbIOGP
